In [2]:
import numpy as np

In [ ]:
import pandas as pd

In [8]:
#for data cleaning, feature engineering, data analyst


#text file,csv(.csv),excel (.xlxs), database
#.read_csv() - for csv file,text file
#.read_excel() - for  excel file
df=pd.read_csv('Data\Data\Employees.csv')

In [9]:
df.head()
df.tail()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0

In [18]:
import pandas as pd

path = 'Data/Data/HR_Dataset Refresh.csv'
hr = pd.read_csv(path)
hr.head(2)

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17

In [ ]:
#feature engineering - creating new features from existing features
'''
feature engineering is the process of using domain knowledge to create new features from existing data. It can help improve the performance of machine learning models by providing them with more relevant information.
for example, if we have a dataset of employee information, we can create a new feature called "tenure" by calculating the difference between the current date and the employee's hire date. This new feature can provide valuable insights into employee retention and turnover.
extracting months year and a dayfrom column
'''

In [ ]:
#.dtype is used to check data type of a column
hr['DateofHire'].dtype

In [20]:
#convert dateofhire to datetime datatype
hr['DateofHire'] = pd.to_datetime(hr['DateofHire'])

In [21]:
#extract year from date
hr['YearofHire'] = hr['DateofHire'].dt.year

In [23]:
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,YearofHire
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1,2011
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17,2015
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3,2011
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15,2008
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2,2011
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15,2012
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19,2014
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19,2013
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4,2009

In [25]:
hr['Hire_Month']=hr['DateofHire'].dt.month
hr['Hire_Day']=hr['DateofHire'].dt.day

In [26]:
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,YearofHire,Hire_Month,Hire_Day
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Exceeds,4.60,5,0,1/17/2019,0,1,2011,7,5
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Fully Meets,4.96,3,6,2/24/2016,0,17,2015,3,30
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Fully Meets,3.02,3,0,5/15/2012,0,3,2011,7,5
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Fully Meets,4.84,5,0,1/3/2019,0,15,2008,1,7
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,2011,7,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,2011,7,11
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,Exceeds,5.00,5,0,1/7/2019,0,15,2012,1,9
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,Fully Meets,3.04,3,4,1/2/2019,0,19,2014,11,10
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,Fully Meets,5.00,4,0,2/25/2019,0,19,2013,9,30
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,Fully Meets,4.46,3,0,1/25/2019,0,4,2009,7,6

In [29]:
hr['Hire_Month_Name']=hr['DateofHire'].dt.month_name()
hr['Hire_Day_Name']=hr['DateofHire'].dt.day_name()

In [30]:
hr

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,YearofHire,Hire_Month,Hire_Day,Hire_Month_Name,Hire_Day_Name
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,5,0,1/17/2019,0,1,2011,7,5,July,Tuesday
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,3,6,2/24/2016,0,17,2015,3,30,March,Monday
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,3,0,5/15/2012,0,3,2011,7,5,July,Tuesday
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,5,0,1/3/2019,0,15,2008,1,7,January,Monday
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,4,0,2/1/2016,0,2,2011,7,11,July,Monday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,4,0,2/1/2016,0,2,2011,7,11,July,Monday
578,"Anderson, Linda",10002,0,0,0,1,5,4,0,57568,...,5,0,1/7/2019,0,15,2012,1,9,January,Monday
579,"Andreola, Colby",10194,0,0,0,1,4,3,0,95660,...,3,4,1/2/2019,0,19,2014,11,10,November,Monday
580,"Athwal, Sam",10062,0,4,1,1,5,3,0,59365,...,4,0,2/25/2019,0,19,2013,9,30,September,Monday
581,"Bachiochi, Linda",10114,0,0,0,3,5,3,1,47837,...,3,0,1/25/2019,0,4,2009,7,6,July,Monday

In [31]:
hr['Gender'].unique()

<StringArray>
['M ', 'F']
Length: 2, dtype: str

In [32]:
hr['Department'].unique()

<StringArray>
[   'Production       ',                'IT/IS', 'Software Engineering',
        'Admin Offices',                'Sales',     'Executive Office']
Length: 6, dtype: str

In [33]:
hr['Department']=hr['Department'].str.strip()  #remove leading and trailing spaces

In [34]:
hr['Gender']=hr['Gender'].str.strip()  #remove leading and trailing spaces

In [35]:
#data analysis
#Groupby and aggregate functions are used while data analysis using python pandas
#GroupBy-> aggregate funtions compulsary
#aggregate functions-> Group by not necessary

In [ ]:
#find total salary of employee associate with each department
'''
syntax:
emp_sal=dataframe.groupby(['column_name1','column_name2'])['column_name3'].agg('aggregate_function')
single grouby
emp_sal=dataframe.groupby('column_name2')['aggcolumn'].sum()

'''

In [37]:
#find total salary of employee associate with each deparment
emp_sal=hr.groupby('Department')['Salary'].sum().reset_index()
emp_sal

             Department    Salary
0         Admin Offices    646127
1      Executive Office    250000
2                 IT/IS   8134411
3            Production  26949336
4                 Sales   2140899
5  Software Engineering   4373364

In [44]:
#find total number of employeees who works in each department
emp_dep= hr.groupby('Department')['EmpID'].count().reset_index()
emp_dep

             Department  EmpID
0         Admin Offices      9
1      Executive Office      1
2                 IT/IS     82
3            Production    419
4                 Sales     31
5  Software Engineering     40

In [45]:
emp_dep= hr.groupby('Department')['EmpID'].count().reset_index().rename(
columns={'EmpID':'Total_Employees'}
)
emp_dep

             Department  Total_Employees
0         Admin Offices                9
1      Executive Office                1
2                 IT/IS               82
3            Production              419
4                 Sales               31
5  Software Engineering               40

In [50]:
emp_dep= hr.groupby('Department').agg(
Total_Employees=(    'EmpID','count'),Total_Salary=('Salary','sum'),
Avg_salary=('Salary','mean')

).reset_index(

)
emp_dep

             Department  Total_Employees  Total_Salary     Avg_salary
0         Admin Offices                9        646127   71791.888889
1      Executive Office                1        250000  250000.000000
2                 IT/IS               82       8134411   99200.134146
3            Production              419      26949336   64318.224344
4                 Sales               31       2140899   69061.258065
5  Software Engineering               40       4373364  109334.100000

In [53]:
#find details of deparment which has less than 40 employees
emp_dep[emp_dep['Total_Employees']<40]

         Department  Total_Employees  Total_Salary     Avg_salary
0     Admin Offices                9        646127   71791.888889
1  Executive Office                1        250000  250000.000000
4             Sales               31       2140899   69061.258065

In [54]:
emp_dep['Avg_salary']=emp_dep['Avg_salary'].map("Rs.{:.2f}".format)
emp_dep

             Department  Total_Employees  Total_Salary    Avg_salary
0         Admin Offices                9        646127   Rs.71791.89
1      Executive Office                1        250000  Rs.250000.00
2                 IT/IS               82       8134411   Rs.99200.13
3            Production              419      26949336   Rs.64318.22
4                 Sales               31       2140899   Rs.69061.26
5  Software Engineering               40       4373364  Rs.109334.10

In [55]:
emp_dep['Total_Salary']=emp_dep['Total_Salary'].map("Rs.{:.2f}".format)
emp_dep

             Department  Total_Employees    Total_Salary    Avg_salary
0         Admin Offices                9    Rs.646127.00   Rs.71791.89
1      Executive Office                1    Rs.250000.00  Rs.250000.00
2                 IT/IS               82   Rs.8134411.00   Rs.99200.13
3            Production              419  Rs.26949336.00   Rs.64318.22
4                 Sales               31   Rs.2140899.00   Rs.69061.26
5  Software Engineering               40   Rs.4373364.00  Rs.109334.10